### PR TITLE
61 fix summary detail appear amt

### PR DESCRIPTION
**Pull request by allison-truhlar**
### What changes did you make?
- I refactored the code to remove the old RecipeBrief component and handleRecipeBriefClick function. The code now passes a function called handleRecipeCardClick down from App.jsx to RecipeCard.jsx. Whenever a recipe card is clicked, the function handleRecipeCardClick in App.jsx is fired. This function sets the recipeDetail state to the recipe data of the clicked card.

### Why did you make these changes?
- To fix a bug that occurred when combining all our branches into development - when we tested the deployment of the development branch on Netlify, the SummaryDetail component was not appearing when you clicked on a recipe card. 

### Visual changes
- None.

### CODE REVIEW

**Review by Emimint — COMMENTED** [review]
Hey @allison-truhlar , it looks good on my side but it is probably better to wait for others' comments. Additionnally, I think you could add some padding on top of the entire component. It was showing like this on my screen:

image


I have change the `SummaryDetail.css` code a little to have it look like this:
image


Here is the updated code :

```
.show-summary-detail {
    padding-top: 1rem;
    transition: transform 1s ease; 
  }

  .show-summary-detail img {
    border-radius: 5px;
  }
```

**Comment by allison-truhlar** [comment]
Thanks, @Emimint, for reviewing and for your suggestion on the CSS! I've added your suggested top padding to the image. I hope to eventually make the image span the entire SummaryDetail component, as in Nghia's design, but this padding definitely helps for the way I've currently displayed the image.

If the component is appearing and disappearing as it should on your end (it should appear when clicking a recipe card, and disappear either when the user clicks on the "x" at the top right, or when the user clicks anywhere on the "blurred" component), could you please mark the PR as "approved" and merge the branch into development? That way I can start working on tweaking the styling of the component further, from the development branch.

**Review by AOA19 — CHANGES_REQUESTED** [review]
@allison-truhlar, 
- I noticed that the video link inside the SummaryDetail component when clicked will download the video onto my computer instead of opening the link. I think this is because the actual link is found inside the original_video_url property not the videoUrl property. Also I know the link will probably open up in a new tab, but if possible maybe we can embed the video? 
- I'm getting an error for the buttons inside of the SummaryDetail component. It's saying the buttons need a type attribute.
- A suggestion, I think the event handler functions inside App.jsx should be refactored and placed inside another component. That component would have the state and logic inside of it and you can pass those props to the child components that need them. This way we can keep App.jsx only for rendering and our code will be easier to maintain.

**Comment by allison-truhlar** [comment]
@AOA19 Thank you for your review! I have added commits to address your first two points, with the exception of embedding the video. I think we should add this as a "nice to have" for now.

I was wondering if you could expand more on your third point - I agree with you, but I'm not entirely sure how to go about implementing this. It sounded like maybe you worked on this with Rob the other night, but I couldn't see the changes in Em's branch. When you say to move the handler functions and state out to another component - would this be a context component?

**Comment by AOA19** [comment]
@allison-truhlar The video link works as it should and yes I agree the embedded video should be a "nice to have". 

As for the third point, I did a little research and we don't necessarily need to use context to move the event handlers and state to another component. We can actually use a Custom Hook. so basically we would create another jsx file name EventHandler (or something a little more descriptive), place the recipeDetail and isDetailShown states inside this new file as well as the three event handler functions, and inside the return statement you would return an object with the properties that you're passing into the rendered components inside of App.jsx. And then inside of App.jsx you would import the Custom hook, call the EventHandler function and destructor the returned object into individual variables. 

I tested this out on my end so I can show you what I mean when you have time. For now I'll approve these changes and we can create a separate issue for refactoring App.jsx

**Review by AOA19 — APPROVED** [review]

**Comment by allison-truhlar** [comment]
@AOA19 Thanks for the further explanation re: the custom hooks. I have not tried this yet, but I will make a new issue to work on it this week (or if you've already worked on it, feel free to claim the issue!)

**Pull request merged**
