### PR TITLE
47 add environmental variables AMT

### PR DESCRIPTION
**Pull request by allison-truhlar**
### What changes did you make?
- Installed the dotenv package
- Added the API key to a .env file and removed it from App.jsx
- Added the .env file to the .gitignore

### Why did you make these changes?
- To avoid exposing our API key publicly on Github

### Visual changes to app
- None

### CODE REVIEW

**Comment by allison-truhlar** [comment]
Note - you'll all need to create a local .env file that you can use when testing locally. For now I've commented out the .env in the .gitignore, so you can all grab the .env file. Once we all have it, then we need to uncomment .env in .gitignore.

**Comment by komalgill0310** [comment]
@allison-truhlar, thank you for creating the .env file for the API key.

### Feedback:

1. The code looks good and is functional.
2. Consider using a more descriptive name for the environment variable, such as "VITE_API_KEY," to enhance clarity and specification.

If you have any suggestions or feedback on how I can improve my feedback, please feel free to share them as well. Let's make this a two-way learning process!

**Comment by allison-truhlar** [comment]
@komalgill0310 Thanks for this suggestion! Clearly I was taking the documentation too literally 😆 I just made this change from VITE_SOME_KEY to VITE_API_KEY.

**Comment by komalgill0310** [comment]
@allison-truhlar thank you for updating. Everything looks good.

**Review by komalgill0310 — APPROVED** [review]

**Pull request merged**
