### PR TITLE
28 build instruction component 

### PR DESCRIPTION
**Pull request by AOA19**
## What changes did you make?
- I created an instruction component that allows the user to open and close the menu. 
- When the menu is open it pushes down the SearchBar component and recipe cards so the Instruction component doesn't overlap. To do this I created a separate function called `toggleInstructionMenu` so whenever the menu is open a margin-top is added to the search bar.
- I placed the `toggleInstructionMenu` (originally inside App.jsx) inside the custom hook file `InstructionMenuHook`
- I adjusted the `padding-right` for the SearchBar component so that it will line up with the `h2` element inside the `Header` component, as well as the recipe cards.

## Why did you make these changes?
- So the user knows how to use the application when they visit the site.
- I created the custom hook `InstructionMenuHook` to keep App.jsx easy to maintain. 

## Screenshots

- Instruction component closed (mobile)
instruction-component-closed_mobile

- Instruction component open (mobile)
instruction-component-open_mobile

- Instruction component closed (desktop)
instruction-component-closed_desktop

- Instruction component open (desktop)
instruction-component-open_desktop

### CODE REVIEW

**Comment by Emimint** [comment]
Looks great on my side @AOA19 🎉 !

**Comment by allison-truhlar** [comment]
@AOA19 Very impressive work on this - I like that you put the toggle function in a separate hook! I noticed just a couple of things when I was testing:

- I tested several different size screens and noticed that sometimes the instruction component overlaps with other components. I think this is due to a combination of the max height of the header component and to the margin on the instruction component. I wonder if nesting the Instruction component inside the Header component, and taking it out of the flow with absolute or sticky positioning (to allow it to extend past the header when expanded) would help with being able both to position the component relative to the other content in the header?

<details><summary>Some example screenshots</summary>

On a tablet turned horizontal
Screenshot 2023-11-16 at 1 51 51 PM

A more edge case - a phone turned horizontal
Screenshot 2023-11-16 at 1 52 36 PM

</details> 

- This is not a "must-do" - I just noticed the chevron and "x" appear a little off-center to my eye with "Instructions." Maybe putting a flex-box around these and aligning items center would fix this.

<details><summary>Screenshot</summary>

Screenshot 2023-11-16 at 1 54 33 PM

</details>

**Comment by AOA19** [comment]
@allison-truhlar, So I tried your suggestion of nesting the instruction component inside of the header component and either positioning it with `sticky` or `absolute`. When the menu was open it would push the header text inside the Header component up instead of pushing the search bar down. So I ended up keeping the Instruction component inside of App.jsx and adjusting the `top` and `margin-top` properties of the Instruction and SearchBar components for various screen heights. Please let me know if you still notice any overlap for various screen sizes.

- Screenshots of similar device sizes you mentioned above 

image1

image2

image3

image4

**Comment by allison-truhlar** [comment]
@AOA19 This looks great on my end! Thanks for working on these changes.

**Review by allison-truhlar — APPROVED** [review]
Thanks for changing the spacing of the instruction component - looks good! I can work on merging this in.

**Pull request merged**
